[project]
name = "mist-v2"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "accelerate",
    "cache",
    "datasets",
    "diffusers",
    "mediapipe",
    "opencv-python",
    "pillow",
    "pynvml",
    "safetensors",
    "scipy",
    "tensorboard",
    "torch==2.7.0",
    "torchmetrics",
    "torchvision",
    "tqdm",
    "transformers",
    "wandb",
    "xformers",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"

[dependency-groups]
dev = []
